# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.cache/wt} [current_project]
set_property parent.project_path {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.srcs/sources_1/imports/new/Registers.vhd}
  {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.srcs/sources_1/imports/new/ALU.vhd}
  {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.srcs/sources_1/imports/MaterialLab2/processor.vhd}
  {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.srcs/sources_1/imports/MaterialLab2/memory.vhd}
  {C:/Users/nicob/Google Drive/Arquitectura de sistemas I/Vivado/TPE_2017/TPE_2017.srcs/sources_1/imports/MaterialLab2/processor_tb.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top processor_tb -part xc7k70tfbv676-1


write_checkpoint -force -noxdef processor_tb.dcp

catch { report_utilization -file processor_tb_utilization_synth.rpt -pb processor_tb_utilization_synth.pb }
